application: recomme-196220
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: mysite.wsgi.application

libraries:
- name: django
  version: "latest"
- name: MySQLdb
  version: 1.2.5
- name: ssl
  version: latest


